# Generated by Django 6.0 on 2025-12-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок карточки', max_length=500, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Описание карточки', max_length=1000, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок сортировки карточек', verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'О конференции',
                'verbose_name_plural': 'О конференции',
                'db_table': 'about',
                'ordering': ['order', 'title'],
            },
        ),
    ]
