version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file:
      - ../.env

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    env_file:
      - ../.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres



volumes:
  postgres_data:
  pgadmin_data:
  