# Generated by Django 6.0 on 2025-12-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное имя участника', max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(help_text='Адрес электронной почты', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('comments', models.TextField(blank=True, help_text='Дополнительные комментарии от участника', max_length=1000, null=True, verbose_name='Комментарий')),
                ('consent', models.BooleanField(default=False, help_text='Согласие на обработку персональных данных', verbose_name='Согласие на обработку данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время регистрации', verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрации',
                'db_table': 'registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
