# Generated by Django 6.0 on 2025-12-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousMeetingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название встречи', max_length=255, verbose_name='Название')),
                ('image', models.ImageField(help_text='Фотография с предыдущей встречи', upload_to='previous_meetings/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок сортировки фотографий', verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Предыдущая встреча',
                'verbose_name_plural': 'Предыдущие встречи',
                'db_table': 'previous_meetings',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
