# Generated by Django 6.0 on 2025-12-17 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('previous_meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previousmeetingsmodel',
            name='title',
        ),
    ]
