# Generated by Django 6.0 on 2025-12-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное имя спикера', max_length=255, verbose_name='Имя')),
                ('position', models.CharField(help_text='Должность спикера', max_length=255, verbose_name='Должность')),
                ('image', models.ImageField(blank=True, help_text='Фотография спикера', null=True, upload_to='speakers/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок сортировки спикеров', verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Спикер',
                'verbose_name_plural': 'Спикеры',
                'db_table': 'speakers',
                'ordering': ['order', 'name'],
            },
        ),
    ]
