# Generated by Django 6.0 on 2025-12-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(help_text='Время проведения мероприятия (например: 09:00 – 09:30)', max_length=50, verbose_name='Время')),
                ('title', models.CharField(help_text='Название мероприятия', max_length=500, verbose_name='Название')),
                ('moderator', models.CharField(blank=True, help_text='Модератор мероприятия (опционально)', max_length=500, null=True, verbose_name='Модератор')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок сортировки мероприятий', verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
                'db_table': 'program',
                'ordering': ['order', 'time'],
            },
        ),
    ]
